server.port=8089
spring.application.name=ms-proveedores

spring.datasource.url=jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=C:/Users/usuario/Downloads/Wallet_MMG8HVEWK688YRH4
spring.datasource.username=SCHEMA_PROVEEDORES
spring.datasource.password=FullStack-Bodega1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=30000

server.error.include-message=always