server.port=8085
spring.application.name=ms-ajuste

spring.datasource.url=jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=C:/Users/usuario/Downloads/Wallet_MMG8HVEWK688YRH4
spring.datasource.username=SCHEMA_AJUSTES
spring.datasource.password=FullStack-Bodega1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

ms.productos.url=http://localhost:8082
ms.kardex.url=http://localhost:8086